from . import test_bemade_fsm_common
from . import test_task_template
from . import test_sale_order
from . import test_fsm_contact_setting
from . import test_fsm_visit
from . import test_task
from . import test_task_report
from . import test_settings
from . import test_equipment
